"""EFE alert level engine."""

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class Alert:
    """Alert generated by the engine."""
    timestamp: float
    system_id: str
    severity: str
    message: str
    efe_value: float


class AlertEngine:
    """Alert engine for monitoring EFE thresholds."""
    
    THRESHOLDS = {
        "EXCELLENT": 0.01,
        "GOOD": 0.02,
        "MODERATE": 0.05,
        "CRITICAL": 0.10,
        "COLLAPSE": 0.0,
    }
    
    def __init__(self):
        self.alerts: List[Alert] = []
        self.last_severity: Dict[str, str] = {}
    
    def check(self, system_id: str, efe_residual: float) -> Optional[Alert]:
        """Check if EFE residual triggers an alert."""
        severity = self._get_severity(efe_residual)
        
        last = self.last_severity.get(system_id, "EXCELLENT")
        if severity == last:
            return None
        
        alert = Alert(
            timestamp=__import__('time').time(),
            system_id=system_id,
            severity=severity,
            message=f"EFE residual crossed into {severity} range",
            efe_value=efe_residual
        )
        
        self.alerts.append(alert)
        self.last_severity[system_id] = severity
        
        return alert
    
    def _get_severity(self, efe: float) -> str:
        """Get severity level from EFE residual value."""
        if efe < 0.01:
            return "EXCELLENT"
        elif efe < 0.02:
            return "GOOD"
        elif efe < 0.05:
            return "MODERATE"
        elif efe < 0.10:
            return "CRITICAL"
        else:
            return "COLLAPSE"
