#!/usr/bin/env python
"""Generate daily gravitational report in TXT format."""

import sys
import os
import json
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from gravineural.core.cno import CovariantNeuralOperator


def get_recommendation(status):
    """Get recommendation based on status."""
    if status == "EXCELLENT":
        return "Continue standard curvature monitoring"
    elif status == "GOOD":
        return "Schedule periodic field equation review"
    elif status == "MODERATE":
        return "Waveform retraining recommended"
    elif status == "CRITICAL":
        return "Emergency metric recalibration required"
    else:
        return "Immediate spacetime recovery protocol"


def generate_daily_report():
    """Generate daily report from gravitational analysis."""
    
    date = datetime.now()
    report_date = date.strftime("%Y%m%d")
    report_time = date.strftime("%H:%M:%S")
    
    results_dir = "results"
    os.makedirs(results_dir, exist_ok=True)
    
    systems = [
        ("Binary Black Hole (R1)", 2.0, 0.5),
        ("Binary Neutron Star (R2)", 1.0, 0.0),
        ("Core-Collapse Supernova (R3)", 15.0, 0.0),
    ]
    
    results = []
    cno = CovariantNeuralOperator()
    stress_energy = [[1,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
    coordinates = [0,10,0,0]
    
    for name, mass, spin in systems:
        result = cno.compute_metric(stress_energy, coordinates)
        
        results.append({
            "system": name,
            "efe_residual": result.ef_e_residual,
            "status": result.status,
            "bianchi_violation": result.bianchi_violation,
            "ricci_scalar": result.ricci_scalar,
            "recommendation": get_recommendation(result.status),
        })
    
    # Generate report content
    report_lines = []
    
    # Header
    report_lines.append("=" * 70)
    report_lines.append("GRAVI-NEURAL Daily Gravitational Report")
    report_lines.append(f"Date: {date.strftime('%Y-%m-%d')}")
    report_lines.append(f"Time: {report_time}")
    report_lines.append(f"Version: 1.0.0 | DOI: 10.5281/zenodo.19871822")
    report_lines.append("=" * 70)
    report_lines.append("")
    
    # Summary
    if results:
        avg_residual = sum(r['efe_residual'] for r in results) / len(results)
        report_lines.append("EXECUTIVE SUMMARY")
        report_lines.append("-" * 50)
        report_lines.append(f"Systems Analyzed:     {len(results)}")
        report_lines.append(f"Average EFE Residual: {avg_residual:.4f}")
        report_lines.append("")
        
        # Status distribution
        status_counts = {}
        for r in results:
            status = r['status']
            status_counts[status] = status_counts.get(status, 0) + 1
        
        report_lines.append("Status Distribution:")
        for status, count in status_counts.items():
            icon = {"EXCELLENT": "🟢", "GOOD": "🟡", "MODERATE": "🟠", "CRITICAL": "🔴", "COLLAPSE": "⚫"}.get(status, "●")
            report_lines.append(f"  {icon} {status:<12} {count}")
        report_lines.append("")
    
    # System details
    report_lines.append("SYSTEM DETAILS")
    report_lines.append("=" * 70)
    
    for r in results:
        icon = {"EXCELLENT": "🟢", "GOOD": "🟡", "MODERATE": "🟠", "CRITICAL": "🔴", "COLLAPSE": "⚫"}.get(r['status'], "●")
        
        report_lines.append("")
        report_lines.append(f"{icon} {r['system']}")
        report_lines.append("-" * 50)
        report_lines.append(f"  EFE Residual:           {r['efe_residual']:.4f}  [{r['status']}]")
        report_lines.append(f"  Bianchi Violation:      {r['bianchi_violation']:.4e}")
        report_lines.append(f"  Ricci Scalar:           {r['ricci_scalar']:.4f}")
        report_lines.append(f"  Recommendation:         {r['recommendation']}")
        report_lines.append("")
    
    # Alert summary
    report_lines.append("ALERT SUMMARY")
    report_lines.append("-" * 50)
    
    critical_systems = [r for r in results if r['status'] in ["CRITICAL", "COLLAPSE", "MODERATE"]]
    if critical_systems:
        report_lines.append("⚠️ Systems requiring attention:")
        for r in critical_systems:
            report_lines.append(f"  - {r['system']}: EFE={r['efe_residual']:.4f} [{r['status']}]")
            report_lines.append(f"    → {r['recommendation']}")
    else:
        report_lines.append("✅ All systems operating within gravitational constraints")
    report_lines.append("")
    
    # Footer
    report_lines.append("=" * 70)
    report_lines.append("End of Report")
    report_lines.append(f"Generated by GRAVI-NEURAL v1.0.0")
    report_lines.append("=" * 70)
    
    # Save report
    report_path = os.path.join(results_dir, f"daily_report_{report_date}.txt")
    with open(report_path, 'w') as f:
        f.write("\n".join(report_lines))
    
    print(f"✅ Daily report saved to: {report_path}")
    
    # Also save JSON version
    json_path = os.path.join(results_dir, f"daily_report_{report_date}.json")
    with open(json_path, 'w') as f:
        json.dump({
            "date": date.isoformat(),
            "systems": results,
            "summary": {
                "total_systems": len(results),
                "average_efe_residual": avg_residual if results else 0,
                "status_distribution": status_counts if results else {}
            }
        }, f, indent=2)
    
    print(f"✅ JSON data saved to: {json_path}")
    
    return report_path


if __name__ == "__main__":
    report_path = generate_daily_report()
    print(f"\n📁 Report location: {report_path}")
    
    # Display report preview
    print("\n" + "=" * 50)
    print("REPORT PREVIEW")
    print("=" * 50)
    with open(report_path, 'r') as f:
        content = f.read()
        print(content[:1000])
        if len(content) > 1000:
            print("\n... (truncated)")
